name: ICS Calendar Filter
slug: ics_calendar_filter
version: "1.1.1"
description: Securely filter and republish ICS calendars
startup: services
boot: auto

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

ports:
  8085/tcp: 8085

options:
  ics_url: ""
  user_agent: "HomeAssistant-ICS-Filter/1.1"
  cache_minutes: 10
  filters: []

schema:
  ics_url: str
  user_agent: str?
  cache_minutes: int?
  filters:
    - field: str
      contains: str?
      regex: str?
